@testable import DistrictData
import DistrictModel
import DistrictNetwork
import Foundation
import XCTest

/// The two Guideline 1.2 moderation calls: blocking a caller, and reading the set.
///
/// ⛔ A SEPARATE FILE FROM `ContactsWriteRepositoryTests`, WHICH HOLDS THE OTHER
/// FIVE CONTACT MUTATIONS, and the split is by more than line count. Those five are
/// all un-retryable (one spends money, one destroys data, one replaces every column,
/// one mints a permanent row); this one is the only contact write on the client that
/// IS idempotent, because it carries the desired state rather than an instruction to
/// flip one. Keeping them apart is what stops the permission leaking sideways.
///
/// ⛔ AND THESE ASSERTIONS ARE THE WHOLE CONTRACT ON THIS CLIENT. Neither route has
/// a contract fixture — that corpus is generated by the server's suite, owned by
/// the Android side, and counted EXACTLY by
/// `ContractManifest.expectedFixtureCount` — so what pins the wire shape is
/// `EndpointTable+Blocking.swift`'s byte-exact body, ``ContactBlockBodies``, and the
/// cases below. See the ⛔ at the top of `ContactBlockBodies.swift`.
final class ContactsBlockRepositoryTests: XCTestCase {
    // MARK: - The write

    func testBlockingByContactIdPostsTheDesiredStateAndAdoptsTheReply() async {
        let transport = RepositoryTransport(json: ContactBlockBodies.blockWrite())

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .setBlocked(workspaceId: "ws_1", subject: .contact("c_1"), blocked: true)

        XCTAssertEqual(result.successOnly?.contactId, "c_1")
        XCTAssertEqual(result.successOnly?.isBlocked, true)
        XCTAssertEqual(transport.requests.first?.method, .post)
        XCTAssertEqual(
            transport.requestedURLs.first,
            "https://www.distronode.com/api/district/contacts/block"
        )
    }

    /// ⛔ THE BY-NUMBER BODY IS ASSERTED BYTE-EXACT BECAUSE A DROPPED KEY IS
    /// INVISIBLE ANY OTHER WAY. ``JSONValue/object(_:)`` removes a nil pair
    /// silently by design, so a `phoneNumber` that never reached the wire looks
    /// identical to one that did until the document itself is compared — and this
    /// is the form an inbox thread whose counterpart never resolved to a `Contact`
    /// row has to use. ⚠️ It lives here rather than in `EndpointTable+Blocking.swift`
    /// because that table asserts one row per `EndpointID` and this is a second
    /// body on an endpoint that already has one.
    func testBlockingByNumberSendsThePhoneAndNoContactId() async {
        let transport = RepositoryTransport(json: ContactBlockBodies.blockWrite())

        _ = await ContactsRepository(client: .repositoryTest(transport))
            .setBlocked(workspaceId: "ws_1", subject: .phoneNumber("+15550101"), blocked: true)

        XCTAssertEqual(
            transport.bodies.first,
            #"{"blocked":true,"phoneNumber":"+15550101","workspaceId":"ws_1"}"#
        )
    }

    /// ⛔ THE DIRECTION TRAVELS IN THE BODY, NOT IN THE PATH, so an unblock is the
    /// same URL with `blocked:false`. A test that only ever sent `true` would pass
    /// against a client that hard-coded it, which is exactly how a screen ends up
    /// with an Unblock button that blocks.
    func testUnblockingSendsFalseOnTheSamePath() async {
        let transport = RepositoryTransport(json: ContactBlockBodies.unblockWrite())

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .setBlocked(workspaceId: "ws_1", subject: .contact("c_1"), blocked: false)

        XCTAssertEqual(
            transport.bodies.first,
            #"{"blocked":false,"contactId":"c_1","workspaceId":"ws_1"}"#
        )
        XCTAssertEqual(
            transport.requestedURLs.first,
            "https://www.distronode.com/api/district/contacts/block"
        )
        XCTAssertEqual(result.successOnly?.isBlocked, false)
    }

    /// ⛔ A NULL `blockedAt` IS THE UNBLOCK'S ANSWER AND MUST DECODE. A non-Optional
    /// field there would decode the block and fail the unblock, leaving the screen
    /// unable to report that a caller had been let back in.
    func testAnUnblockReplyCarriesANullTimestampRatherThanFailingToDecode() async {
        let transport = RepositoryTransport(json: ContactBlockBodies.unblockWrite())

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .setBlocked(workspaceId: "ws_1", subject: .contact("c_1"), blocked: false)

        XCTAssertNil(result.successOnly?.blockedAt)
        XCTAssertEqual(result.successOnly?.row.isBlocked, false)
    }

    /// ⚠️ THE REPLY'S `contactId` IS ADOPTED RATHER THAN THE REQUEST'S. A caller
    /// that blocked by number does not know the id until this body arrives — the
    /// server upserts the contact — so this is the only place the identity of the
    /// row that was just blocked exists.
    func testTheReplysContactIdIsAdoptedWhenTheRequestCarriedOnlyANumber() async {
        let transport = RepositoryTransport(json: ContactBlockBodies.blockWrite(contactId: "c_upserted"))

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .setBlocked(workspaceId: "ws_1", subject: .phoneNumber("+15550102"), blocked: true)

        XCTAssertEqual(result.successOnly?.contactId, "c_upserted")
    }

    func testAWriteThatDoesNotAffirmSuccessIsADecodeFailure() async {
        let transport = RepositoryTransport(json: ContactBlockBodies.blockWrite(success: false))

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .setBlocked(workspaceId: "ws_1", subject: .contact("c_1"), blocked: true)

        XCTAssertEqual(result.failureOnly, .decoding("ContactBlockResponse did not affirm success=true"))
    }

    /// ⛔ A 404 IS NOT FOLDED INTO SUCCESS, UNLIKE `contacts/delete`. There the row
    /// being gone is the outcome the caller asked for; here it means nothing was
    /// blocked, and reporting a block that did not happen is the one claim
    /// Guideline 1.2 is about.
    func testA404IsAFailureRatherThanASilentSuccess() async {
        let transport = RepositoryTransport(
            json: #"{"success":false,"error":"Contact not found."}"#,
            status: 404
        )

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .setBlocked(workspaceId: "ws_1", subject: .contact("c_missing"), blocked: true)

        XCTAssertEqual(result.failureOnly, .http(status: 404, message: "Contact not found."))
    }

    /// ⚠️ A 403 IS THE ROLE, AND THE ROUTE'S OWN SENTENCE REACHES THE SCREEN INTACT.
    /// Every contact mutation excludes `viewer` server-side.
    func testA403KeepsTheRoutesOwnSentence() async {
        let transport = RepositoryTransport(
            json: #"{"error":"Insufficient role for this workspace."}"#,
            status: 403
        )

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .setBlocked(workspaceId: "ws_1", subject: .contact("c_1"), blocked: true)

        XCTAssertEqual(
            result.failureOnly,
            .http(status: 403, message: "Insufficient role for this workspace.")
        )
    }

    // MARK: - The read

    func testTheBlockedListDecodesItsRows() async {
        let body = ContactBlockBodies.blockedList([
            ContactBlockBodies.row(contactId: "c_1"),
            ContactBlockBodies.row(contactId: "c_9", name: "Jordan Fox", phoneNumber: #""+15550199""#),
        ])
        let transport = RepositoryTransport(json: body)

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .blocked(workspaceId: "ws_1")

        XCTAssertEqual(result.successOnly?.map(\.contactId), ["c_1", "c_9"])
        XCTAssertEqual(result.successOnly?.last?.phoneNumber, "+15550199")
        XCTAssertEqual(result.successOnly?.allSatisfy(\.isBlocked), true)
        XCTAssertEqual(transport.requests.first?.method, .get)
        XCTAssertEqual(
            transport.requestedURLs.first,
            "https://www.distronode.com/api/district/contacts/blocked?workspaceId=ws_1"
        )
    }

    /// ⛔ AN EMPTY LIST IS A SUCCESS AND IS THE COMMON ANSWER. Reading it as a
    /// failure — or reading a failure as an empty list — would offer an Unblock
    /// control on somebody who is still blocked and hide the badge that says so.
    func testAnEmptyBlockedListIsARealAnswer() async {
        let transport = RepositoryTransport(json: ContactBlockBodies.blockedList())

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .blocked(workspaceId: "ws_1")

        XCTAssertEqual(result.successOnly?.isEmpty, true)
        XCTAssertNil(result.failureOnly)
    }

    /// ⚠️ EMAIL-FIRST CONTACTS ARE BLOCKABLE AND CARRY NO NUMBER. A non-Optional
    /// `phoneNumber` would fail the whole read on one such row.
    func testAnEmailOnlyContactDecodesWithNoPhoneNumber() async {
        let transport = RepositoryTransport(
            json: ContactBlockBodies.blockedList([ContactBlockBodies.emailOnlyRow()])
        )

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .blocked(workspaceId: "ws_1")

        XCTAssertEqual(result.successOnly?.count, 1)
        XCTAssertNil(result.successOnly?.first?.phoneNumber)
        XCTAssertEqual(result.successOnly?.first?.isBlocked, true)
    }

    func testAReadThatDoesNotAffirmSuccessIsADecodeFailure() async {
        let transport = RepositoryTransport(json: #"{"success":false,"blocked":[]}"#)

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .blocked(workspaceId: "ws_1")

        XCTAssertEqual(result.failureOnly, .decoding("BlockedContactsResponse did not affirm success=true"))
    }

    /// ⛔ A ROW THE SERVER SENDS WITH A NULL TIMESTAMP IS RETURNED AS SENT. The
    /// route is the authority on which of its own rows count; filtering here would
    /// make this method's answer disagree with the next read's.
    func testARowWithNoTimestampIsReturnedRatherThanFilteredOut() async {
        let transport = RepositoryTransport(
            json: ContactBlockBodies.blockedList([
                ContactBlockBodies.row(contactId: "c_stale", blockedAt: "null"),
            ])
        )

        let result = await ContactsRepository(client: .repositoryTest(transport))
            .blocked(workspaceId: "ws_1")

        XCTAssertEqual(result.successOnly?.count, 1)
        XCTAssertEqual(result.successOnly?.first?.isBlocked, false)
    }
}
