import Foundation

/// Minimal, VALID `contacts/block` and `contacts/blocked` bodies.
///
/// ⛔ THESE ARE NOT CONTRACT FIXTURES AND MUST NOT DRIFT INTO PRETENDING TO BE,
/// which is the same statement `DeskBodies` opens with and for the same reason.
/// What pins a wire shape in this project is the shared contract corpus and its
/// strict decode/re-encode walk; that corpus is generated by the server's own
/// suite, is owned by the Android side, and `ContractManifest.expectedFixtureCount`
/// asserts EXACTLY the files on disk — so a `.json` added from here would red this
/// suite AND the Android one until a constant moved in each. The blocking routes
/// therefore sit where `createContact` sits: pinned by the route source, by the
/// byte-exact body in `EndpointTable+Blocking.swift`, and by these documents.
///
/// ⛔ THE KEY NAMES ARE THE CONTRACT, SO THEY ARE IN ONE FILE WITH THE NAMES SPELLED
/// OUT rather than scattered through assertions. The four the server owes are
/// `contactId`, `name`, `phoneNumber` and `blockedAt` on the write, and the same
/// four inside `blocked[]` on the read.
///
/// ⚠️ `phoneNumber` IS EXERCISED BOTH PRESENT AND EXPLICITLY NULL. Contacts are
/// email-first and a phone-less contact is legal (see the ⚠️ on
/// ``Contact/phoneNumber``), so a corpus that only ever showed a number would let a
/// non-Optional DTO ship and fail on the first email-only caller anyone blocked.
///
/// ⚠️ ITS OWN FILE because two suites read it — the repository tests and the model
/// tests — which is the same reason `DeskBodies` and `NumberTestBodies` have one.
enum ContactBlockBodies {
    /// The write's reply. ⚠️ `blockedAt` is a literal so an UNBLOCK can pass `null`.
    static func blockWrite(
        contactId: String = "c_1",
        name: String = "Casey Rivera",
        phoneNumber: String = #""+15550101""#,
        blockedAt: String = #""2026-09-16T14:02:00.000Z""#,
        success: Bool = true
    ) -> String {
        #"""
        {"success":\#(success),"contactId":"\#(contactId)","name":"\#(name)",
         "phoneNumber":\#(phoneNumber),"blockedAt":\#(blockedAt)}
        """#
    }

    /// The reply to an UNBLOCK: same four fields, `blockedAt` null.
    ///
    /// ⛔ A SUCCESS, NOT A FAILURE, AND THE NULL IS THE ANSWER. A DTO with a
    /// non-Optional `blockedAt` decodes the block and fails the unblock, which is
    /// the shape that would leave a caller unable to report that a caller had been
    /// let back in.
    static func unblockWrite(contactId: String = "c_1") -> String {
        blockWrite(contactId: contactId, blockedAt: "null")
    }

    /// One row of the blocked list.
    static func row(
        contactId: String,
        name: String = "Casey Rivera",
        phoneNumber: String = #""+15550101""#,
        blockedAt: String = #""2026-09-16T14:02:00.000Z""#
    ) -> String {
        #"""
        {"contactId":"\#(contactId)","name":"\#(name)","phoneNumber":\#(phoneNumber),
         "blockedAt":\#(blockedAt)}
        """#
    }

    /// The list read.
    ///
    /// ⚠️ AN EMPTY ARRAY IS THE DEFAULT ARGUMENT DELIBERATELY, because it is the
    /// commonest real answer: most workspaces have blocked nobody. The test that
    /// uses it is asserting that this is a SUCCESS rather than a failure.
    static func blockedList(_ rows: [String] = []) -> String {
        #"{"success":true,"blocked":[\#(rows.joined(separator: ","))]}"#
    }

    /// A blocked contact with no phone number at all.
    ///
    /// ⚠️ EMAIL-FIRST IS NOT AN EDGE CASE HERE. `findOrCreateContactByEmail` writes
    /// rows with a null `phoneNumber`, and an inbound email is as blockable as an
    /// inbound call.
    static func emailOnlyRow(contactId: String = "c_2") -> String {
        row(contactId: contactId, name: "ada@example.com", phoneNumber: "null")
    }
}
