import Foundation

public extension TypedEndpoints {
    /// The two Guideline 1.2 moderation routes.
    ///
    /// ⛔ NEVER UNTYPED: ``ContactBlockResponse``, ``BlockedContactsResponse`` and the
    /// two ``ContactsRepository`` methods belong with the descriptors, so no screen can
    /// reach these routes and get bytes back.
    ///
    /// ⛔ AND NEITHER HAS A CONTRACT FIXTURE, WHICH IS A DECISION RATHER THAN AN
    /// OVERSIGHT. `ContractManifest.expectedFixtureCount` asserts EXACTLY the number of
    /// `.json` files in the shared corpus, and that corpus is generated by the
    /// server's own suite and owned by the Android side. A fixture added from here
    /// would red BOTH clients until the constant moved on each. So these two are pinned
    /// the way the contact WRITES already are — `createContact` has no fixture either
    /// (see the ⚠️ on ``ContactCreateResponse``) — by the route source, by
    /// `EndpointTableTests`' byte-exact body, and by `ContactsBlockRepositoryTests`
    /// against ``ContactBlockBodies``.
    ///
    /// ⚠️ ITS OWN FILE RATHER THAN TWO MORE LINES IN `EndpointClassification.swift`,
    /// for the reason `EndpointClassification+Desk.swift` gives: that file is at
    /// SwiftLint's 500-line ceiling and the commentary on those lists is the point of
    /// them. ⛔ A family declared here and not unioned into ``TypedEndpoints/all``
    /// fails `EndpointSurfaceTests`' partition assertion rather than defaulting to
    /// "raw".
    static let blocking: Set<EndpointID> = [
        .setContactBlocked,
        .blockedContacts,
    ]
}
