import Crypto
import Foundation

/// PKCE (RFC 7636) for the native login handshake.
///
/// ⛔ PKCE IS LOAD-BEARING HERE, NOT CEREMONY. The authorization code comes back
/// over the `districtai://auth` custom scheme, and any app on the device can
/// claim a custom scheme. PKCE is what makes an
/// intercepted code worthless: the challenge is sent up front, the verifier
/// never leaves the process, and the exchange requires the verifier.
/// `ASWebAuthenticationSession` narrows the window further by intercepting the
/// callback in-session, but it does not remove the need for this.
///
/// ⛔ THE CHALLENGE IS THE DIGEST OF THE VERIFIER *STRING*, NOT OF DECODED
/// BYTES. RFC 7636 defines `code_challenge = base64url(SHA256(ASCII(verifier)))`
/// and the server's `deriveCodeChallenge` implements exactly that
/// (`crypto.subtle.digest("SHA-256", new TextEncoder().encode(v))`). Hashing
/// anything else produces a well-formed value that is always wrong, and the
/// server reports it as one opaque `invalid_grant` — indistinguishable from a
/// replayed or expired code. There is no log line anywhere that would say "your
/// challenge encoding is wrong", which is why `PKCEVectorTests` pins this
/// against vectors generated by the server's own implementation.
///
/// ⛔ BASE64URL WITHOUT PADDING. A retained `=` yields a 44-character challenge,
/// which fails the server's `isValidCodeChallenge` (`^[A-Za-z0-9\-_]{43}$`) at
/// authorize time — before any code is issued.
public enum PKCE {
    /// Bytes of entropy in a verifier.
    ///
    /// 32 bytes base64url-encodes to 43 characters, which is RFC 7636's minimum
    /// verifier length and the floor of the server's `isValidCodeVerifier`
    /// (43...128). The minimum is chosen deliberately: it is already 256 bits of
    /// entropy, and a longer verifier buys nothing while moving closer to the
    /// 128-character ceiling.
    public static let verifierByteCount = 32

    /// Bytes of entropy in the `state` parameter.
    ///
    /// ⚠️ `state` IS NOT PART OF PKCE and does a different job: it binds the
    /// callback to the request this app started, so a code injected by another
    /// app, or an old callback replayed out of history, is rejected before it is
    /// ever exchanged.
    public static let stateByteCount = 32

    /// A fresh verifier, its S256 challenge and a `state` value, for one login
    /// attempt.
    public static func newChallenge(using random: any RandomByteSource = CryptoRandomByteSource()) -> PKCEChallenge {
        let verifier = Base64URL.encode(random.bytes(verifierByteCount))
        return PKCEChallenge(
            verifier: verifier,
            challenge: deriveChallenge(for: verifier),
            state: newState(using: random)
        )
    }

    /// A fresh `state` value on its own.
    public static func newState(using random: any RandomByteSource = CryptoRandomByteSource()) -> String {
        Base64URL.encode(random.bytes(stateByteCount))
    }

    /// `base64url(SHA-256(verifier))`.
    ///
    /// Exposed so `PKCEVectorTests` can assert it against the server's output
    /// for the same inputs, rather than only round-tripping against itself —
    /// which would agree with itself while both sides were wrong.
    ///
    /// ⚠️ UTF-8 BYTES, WHICH IS WHAT THE SERVER HASHES. RFC 7636 says
    /// `ASCII(code_verifier)` and the two encodings are identical over the
    /// verifier alphabet, so the distinction cannot matter for a well-formed
    /// verifier. Where it could matter — a caller passing something outside the
    /// alphabet — matching `TextEncoder` exactly is the behaviour that agrees
    /// with the only implementation whose opinion counts.
    public static func deriveChallenge(for verifier: String) -> String {
        Base64URL.encode(Data(SHA256.hash(data: Data(verifier.utf8))))
    }
}

/// One login attempt's secrets.
///
/// ⛔ THE VERIFIER MUST SURVIVE THE TRIP OUT TO `ASWebAuthenticationSession` AND
/// BACK, AND MUST NEVER BE PERSISTED. It is held in memory by the login
/// controller in `App/`. A login attempt that does not complete before the
/// process dies is simply restarted, which costs the user a tap and avoids
/// writing a live credential-exchange secret to disk.
public struct PKCEChallenge: Sendable, Equatable {
    public let verifier: String
    public let challenge: String
    public let state: String

    public init(verifier: String, challenge: String, state: String) {
        self.verifier = verifier
        self.challenge = challenge
        self.state = state
    }
}

/// Where PKCE's entropy comes from.
///
/// ⚠️ A SEAM SO TESTS CAN BE DETERMINISTIC, NOT SO PRODUCTION CAN BE
/// CONFIGURED. There is exactly one production implementation and it is the
/// default argument everywhere; the protocol exists because
/// "`newChallenge` encodes its bytes correctly" is otherwise unassertable
/// without reimplementing base64url in the test.
public protocol RandomByteSource: Sendable {
    /// Exactly `count` cryptographically secure random bytes.
    func bytes(_ count: Int) -> Data
}

/// The production entropy source.
///
/// ⛔ swift-crypto's CSPRNG, NOT `SystemRandomNumberGenerator`. The standard
/// library's generator is documented as cryptographically secure only "whenever
/// possible", which is a guarantee with a hole in it for a value whose
/// unpredictability is the entire security argument for PKCE.
/// `SymmetricKey(size:)` is generated from the platform's cryptographic RNG on
/// every platform swift-crypto supports — `SecRandomCopyBytes` on Darwin,
/// BoringSSL's `RAND_bytes` on Linux — which is the same guarantee
/// `SecureRandom` gives the Kotlin client.
public struct CryptoRandomByteSource: RandomByteSource {
    public init() {}

    public func bytes(_ count: Int) -> Data {
        SymmetricKey(size: SymmetricKeySize(bitCount: count * 8)).withUnsafeBytes { Data($0) }
    }
}
