import ContractGateSupport
@testable import DistrictAuthCore
import Foundation
import XCTest

/// Asserts this module's PKCE derivation against vectors produced by the
/// SERVER's own TypeScript implementation.
///
/// ⛔ WHY NOT JUST TEST THE SWIFT AGAINST ITSELF. A self-consistency test
/// (derive, derive again, compare) passes happily while both the challenge and
/// the expectation are wrong in the same way. The failure that actually happens
/// in production is DISAGREEMENT BETWEEN THE TWO LANGUAGES, and the server
/// reports it as a single opaque `invalid_grant` indistinguishable from a
/// replayed or expired code. There is no log line, anywhere, that would say
/// "your challenge encoding is wrong" — so this is the only place that can catch
/// it. `PkceVectorTest.kt` is the Kotlin half of the same idea.
///
/// ⚠️ Vectors are regenerated by the server's contract suite, never by hand.
final class PKCEVectorTests: XCTestCase {
    private struct Vector: Decodable {
        let verifier: String
        let challenge: String
    }

    /// ⛔ A THROWN LOAD IS THE POINT. `ContractFixtures` refuses to return an
    /// empty set, so a broken cross-folder path reds
    /// this suite instead of vacuously passing every assertion below.
    private func loadVectors() throws -> [Vector] {
        let data = try ContractFixtures.read("district-pkce-vectors.json")
        return try JSONDecoder().decode([Vector].self, from: data)
    }

    func testFixtureIsNotEmpty() throws {
        let vectors = try loadVectors()
        XCTAssertFalse(vectors.isEmpty, "the PKCE vector fixture contains no vectors")
        print("PKCE vectors verified: \(vectors.count)")
    }

    func testSwiftDerivationMatchesTheServerForEveryVector() throws {
        for vector in try loadVectors() {
            XCTAssertEqual(
                PKCE.deriveChallenge(for: vector.verifier),
                vector.challenge,
                """
                PKCE challenge mismatch for a \(vector.verifier.count)-char verifier. The client and
                server disagree, which means EVERY login fails with an opaque invalid_grant. Check:
                digest of the verifier STRING (not decoded bytes), base64url (not standard base64),
                and NO padding.
                """
            )
        }
    }

    func testFixtureIncludesTheRFC7636ReferenceVector() throws {
        // Independent confirmation that the SERVER is right too, not merely that
        // the two sides agree with each other.
        let vectors = try loadVectors()
        XCTAssertTrue(
            vectors.contains { $0.verifier == "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk" },
            "the RFC 7636 reference verifier should be among the generated vectors"
        )
    }

    func testEveryFixtureVerifierSatisfiesTheServersOwnShapeCheck() throws {
        // The generator emits the boundary cases (43 and 128 characters, and the
        // full unreserved alphabet), so this doubles as a check that the
        // re-implemented `isValidVerifier` agrees with `isValidCodeVerifier`.
        for vector in try loadVectors() {
            XCTAssertTrue(PKCE.isValidVerifier(vector.verifier), "verifier rejected: \(vector.verifier)")
            XCTAssertTrue(PKCE.isValidChallenge(vector.challenge), "challenge rejected: \(vector.challenge)")
        }
    }
}
